if &compatible
  set nocompatible
endif

" Plugins: {{{
call plug#begin('~/.vim/plugged')

Plug 'junegunn/vim-easy-align'
Plug 'junegunn/fzf'
Plug 'preservim/tagbar'
Plug 'sgur/vim-editorconfig'

Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'

Plug 'fatih/vim-go'
Plug 'nsf/gocode'

Plug 'airblade/vim-gitgutter'
Plug 'mhinz/vim-signify'

Plug 'ryanoasis/vim-devicons'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

Plug 'dracula/vim'

Plug 'wakatime/vim-wakatime'

call plug#end()
" }}}

filetype plugin indent on
syntax enable

function! s:load_config()
  for path in glob($HOME . '/.vim/rc/*.vim', 1, 1)
    exec "source " . path
  endfor
endfunction

call s:load_config()

" Completion {{{
let g:asyncomplete_auto_popup = 1
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <cr>    pumvisible() ? asyncomplete#close_popup() : "\<cr>"
set completeopt=menuone,noinsert,noselect,preview
" }}}

let g:airline#extensions#tabline#enabled = 1

set background=dark
colorscheme dracula

" vim: ts=2 sts=2 sw=2 et fdm=marker
